name: Test MTA works on various platforms

on:
  push:
    branches:
      - main
      - solution
  pull_request:
    branches:
      - main
      - solution

jobs:
  verify-mta-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Run MTA
        run: docker run -v $(pwd):/opt/project:z -u $(id -u):$(id -g) quay.io/edeandrea/mta-cli:latest
      - name: Assert MTA output
        run: .github/workflows/scripts/assertMta.sh

  verify-mta-macos-10:
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install docker # Taken from https://github.com/actions/virtual-environments/issues/1143#issuecomment-652264388
        run: |
          mkdir -p ~/.docker/machine/cache
          curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
          brew install docker docker-machine
          docker-machine create --driver virtualbox default
          docker-machine env default
      - name: Run MTA
        run: docker run -v $(pwd):/opt/project:z -u $(id -u):$(id -g) quay.io/edeandrea/mta-cli:latest
      - name: Assert MTA output
        run: .github/workflows/scripts/assertMta.sh

  verify-mta-macos-11:
    runs-on: macos-11
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install docker # Taken from https://github.com/actions/virtual-environments/issues/1143#issuecomment-652264388
        run: |
          mkdir -p ~/.docker/machine/cache
          curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
          brew install docker docker-machine
          docker-machine create --driver virtualbox default
          docker-machine env default
      - name: Run MTA
        run: docker run -v $(pwd):/opt/project:z -u $(id -u):$(id -g) quay.io/edeandrea/mta-cli:latest
      - name: Assert MTA output
        run: .github/workflows/scripts/assertMta.sh