name: Test MTA works on various platforms

on:
  push:
    branches:
      - main
      - solution
  pull_request:
    branches:
      - main
      - solution

jobs:
  verify-mta-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Run MTA
        run: docker run -v $(pwd):/opt/project:z -u $(id -u):$(id -g) quay.io/edeandrea/mta-cli:latest
      - name: Assert MTA output
        run: .github/workflows/scripts/assertMta.sh

  verify-mta-macos-10:
    runs-on: macos-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Run MTA
        run: docker run -v $(pwd):/opt/project:z -u $(id -u):$(id -g) quay.io/edeandrea/mta-cli:latest
      - name: Assert MTA output
        run: .github/workflows/scripts/assertMta.sh

  verify-mta-macos-11:
    runs-on: macos-11
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Run MTA
        run: docker run -v $(pwd):/opt/project:z -u $(id -u):$(id -g) quay.io/edeandrea/mta-cli:latest
      - name: Assert MTA output
        run: .github/workflows/scripts/assertMta.sh